### ISSUE TITLE
FrankDoc does not handle javadoc tags properly

### ISSUE THREAD

**Issue by jjansenvr** [frankframework/frank-doc#196] opened 2024-07-31 10:40 UTC
I use FF-version="8.2.0"

In the xsd I see {@code } instead of useful info
![image](https://github.com/user-attachments/assets/1c6ad631-8af8-4b26-a3e5-754b91f18c50)

When hovering the Directory listener (in vscode) I do not see any info. Other elements do show the extra information (as shown above) 
DirectoryListener is part of the xsd but the Type does not seem to be defined with all info

the links in the frankdoc to the java doc pages does not work for elements that are part of extensions

**Comment by nielsm5** [comment] 2024-08-12 18:20
Duplicate of #7273

**Comment by thomaspj10** [comment] 2024-08-23 09:45
The issue is pretty obvious. The XML in the code block is shown as HTML, while it should just be a String. This can be achieved by escaping all the HTML inside a code block.

![Image](https://github.com/user-attachments/assets/82c17bcf-67ba-4358-b244-8f1afc5c9882)

**Closed** 2024-08-28 09:50 UTC
Labels: doclet
